### ISSUE TITLE
Can't check token and MS Service doesn't start

### ISSUE THREAD

**Issue by solik00** [infrabot-io/infrabot#2]
Hi!
1 - MS Service do not start, and app show empty window
2 -
<img width="959" alt="Screenshot 2021-12-21 at 14 33 09" src="https://user-images.githubusercontent.com/96188859/146931426-4fc8b2cc-8e7e-4756-9100-8fa7fc5a6231.png">

**Comment by akshinmustafayev** [comment]
Добрый день,

Токен в конфигурационном файле указан не верно. Необходимо указать валидный токен в файле config.json. Можете сконфигурировать с помощью утилиты InfraBot Config Editor. Пример валидного токена указано в тексте ошибки "A valid token looks like".

Токен необходимо получить от телеграм используя этот мануал: https://infrabot-io.github.io/documentation/configurebot.html

**Comment by schokk89** [comment]
Аналогичная проблема, токен указываю верный. Пример токена: "5359548914:AAF7qMBZFEC3z0IBt5pw6oR5qFZy78Pf1Eg". Если уменьшить до 7 цифр начало токена то принимает токен из конфига но естественно ругается "Telegram.Bot.Exceptions.ApiRequestException: Unauthorized"

**Comment by akshinmustafayev** [comment]
Проблему подтверждаю.
Причина в изменении длины токена и используемом старой версии Nuget пакета. 
Во время разработки приложения токен имел меньшую длину, сейчас произошли значительные изменения как и в API так и в самом пакете TelegramBot.
Необходимо полное переписывание приложения под новую версию TelegramBot.

**Comment by akshinmustafayev** [comment]
Новая версия приложения создана.
Сейчас приложение на стадии тестирования. После обновления документации и исправлении багов будет выпущен новый релиз.

**Comment by akshinmustafayev** [comment]
New version of the application has been published. Go to the release page and [download](https://github.com/infrabot-io/infrabot/releases) installation file.
Documentation is here: [https://infrabot-io.github.io](https://infrabot-io.github.io)
